name: Test

on:
  pull_request_target:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --immutable
      - run: yarn test --coverage
      - uses: codecov/codecov-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
